/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_weshape3d_myapplication_MyJNI */

#ifndef _Included_com_weshape3d_myapplication_MyJNI
#define _Included_com_weshape3d_myapplication_MyJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_weshape3d_myapplication_MyJNI
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_weshape3d_myapplication_MyJNI_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_weshape3d_myapplication_MyJNI
 * Method:    increaseArray
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_weshape3d_myapplication_MyJNI_increaseArray
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
